
services:

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: payment-system-test
    container_name: payment-system
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_PASSWORD: 'batman123'
      MYSQL_ROOT_PASSWORD: 'batman123'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./database_data:/var/lib/mysql
    networks:
      - app-network
  ###< doctrine/doctrine-bundle ###
  nginx:
    image: nginx:1.25-alpine
    container_name: payment-test-nginx
    restart: unless-stopped
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
    driver: local
